import { AppBar, Box, Divider, Paper, Toolbar, Typography } from '@mui/material'
import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import WithSidePanel, { SidePanelSelection } from './_withsidepanel'
import CustomAppBar from './_customAppBar'
import styles from '../styles/About.module.css'

const MUI_LICENSE = `The MIT License (MIT)

Copyright (c) 2014 Call-Em-All

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`

const NEXT_LICENSE = `The MIT License (MIT)

Copyright (c) 2022 Vercel, Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`

const REACT_LICENSE = `MIT License

Copyright (c) Facebook, Inc. and its affiliates.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>tkh HP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <CustomAppBar />
      </header>

      <main>
        <WithSidePanel selection={SidePanelSelection.ABOUT}>
          <Box sx={{ padding: 2}}>
            <Typography variant="h5" component="div">このページについて</Typography>

            <Typography variant="body1" color="text.secondary">
              オープンソースライセンス
            </Typography>
            
            <Typography variant="h6" sx={{ mt: 4, mb: 2 }}>
              MUI Core
            </Typography>
            <Paper variant="outlined" sx={{ pl: 2, pr: 2 }}>
              <pre className={styles.license}>{MUI_LICENSE}</pre>
            </Paper>
            
            <Typography variant="h6" sx={{ mt: 4, mb: 2 }}>
              Next.js
            </Typography>
            <Paper variant="outlined" sx={{ pl: 2, pr: 2 }}>
              <pre className={styles.license}>{NEXT_LICENSE}</pre>
            </Paper>
            
            <Typography variant="h6" sx={{ mt: 4, mb: 2 }}>
              React.js
            </Typography>
            <Paper variant="outlined" sx={{ pl: 2, pr: 2 }}>
              <pre className={styles.license}>{REACT_LICENSE}</pre>
            </Paper>
          </Box>
        </WithSidePanel>
      </main>
    </div>
  )
}

export default About
