import { AppBar, Box, Card, CardContent, CardMedia, Chip, Divider, ImageList, ImageListItem, Stack, Toolbar, Typography } from '@mui/material'
import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import WithSidePanel, { SidePanelSelection } from './_withsidepanel'
import CustomAppBar from './_customAppBar'
import styles from '../styles/Dashboard.module.css'

const dashboardItems = [
  {
    img: {
      path: "/autoline.png",
      alt: "autoline",
    },
    title: "自動線画生成",
    desc: "「ラフスケッチ」を「線画」に変換する画像処理について研究しています．",
    tags: ["研究"],
  },
  {
    img: {
      path: "/cat.JPG",
      alt: "Cat",
    },
    title: "猫派",
    desc: "どちらかといえば猫派です．写真は飯野山（讃岐富士）で撮影",
    tags: [],
  },
  {
    img: {
      path: "/mt_tsurugi.JPG",
      alt: "Mt. Tsurugi",
    },
    title: "登山",
    desc: "たまに登山します．写真は剣山山頂．",
    tags: ["趣味"],
  },
  {
    img: {
      path: "/konsento_outlet_plug.png",
      alt: "Power outlet",
    },
    title: "電気工事士",
    desc: "第二種電気工事士取りました",
    tags: ["特技"],
  },
  {
    img: {
      path: "/car3_gray.png",
      alt: "Car",
    },
    title: "ドライブ",
    desc: "運転が好きです．",
    tags: ["趣味"],
  },
  {
    img: {
      path: "/CAN.JPG",
      alt: "electronics",
    },
    title: "電子工作",
    desc: "AVRとかSHとかRXとか",
    tags: ["趣味"],
  },
  {
    img: {
      path: "/drink_beer_can_long.png",
      alt: "beer",
    },
    title: "酒",
    desc: "ビール等をよく飲みます．アサヒ派",
    tags: ["好物"],
  },
]

const Dashboard: NextPage = () => {
  return (
    <div>
      <Head>
        <title>tkh HP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <CustomAppBar />
      </header>

      <main>
        <WithSidePanel selection={SidePanelSelection.DASHBOARD}>
          <Box sx={{ padding: 2}}>
            <Typography variant="h5" component="div">概略</Typography>
            <Typography variant="body1" color="text.secondary">こんな人です．</Typography>
            <ImageList variant="masonry" cols={3} gap={12}>
              {
                dashboardItems.map((item, i, _) => (
                  <ImageListItem key={`dashboard-card-${i}`}>
                    <Card variant="outlined" className={styles.card}>
                      <CardMedia
                        component="img"
                        image={item.img.path}
                        alt={item.img.alt}/>
                      {/* <Divider/> */}
                      <CardContent>
                        <Stack direction="row" spacing={2}>
                          {
                            item.tags.map((tag, j, _) => (
                              <Chip
                                label={tag}
                                sx={{ lineHeight: "normal" }}
                                key={`dashboard-card-tag-${j}`}/>
                            ))
                          }
                        </Stack>
                        <Typography variant="h5" component="div">{item.title}</Typography>
                        <Typography variant="body2" color="text.secondary">{item.desc}</Typography>
                      </CardContent>
                    </Card>
                  </ImageListItem>
                ))
              }
            </ImageList>
          </Box>
        </WithSidePanel>
      </main>
    </div>
  )
}

export default Dashboard
